language: cpp

branches:
  only:
    - master
    - coverity_scan

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "DZrUb/bL6NIXTsNyyK8UFjuj4tmZmRILk8mcYXTepAHcJevOmRtSi/fiRJWp9N36DI30pGbKwme2BA9M8a+DsxNaoPklLa5pAVBPGhpLxIS9pIms+ZzSbxYvToXqTTEWPqmHdr3a7oxiSjG1z4WiStYQmbhQFwZvgAO8cOL9gBc2WV1yZMEqkHR6zvOp8LbGYWcvz29tnQ5ORhX0M2DjLlZ3id9DWInkkC/WerbPtW6Z9R41oGxNBI7WWaVG19e0VwkHOPbjRJHS6ftZw1kIiNkbwCl6Lnyyn4ack7mB+joECXauCV5qkwMmgAsTi6kouSwUoMuyPb90jFOrpkdGfosNAhSnN8x0BY3eLIR9imInOnbs9+YEoHcXGBxVZ8zXZxlXPDYuB72V+OKhvrZoX+IVG6rCE+yf7FPy8BKVMJpNOEoGkyDiNawfDnbYhqso5IDZIt8lT2bBb2M1VFy3hrNt8fa36MJParzkJp1LdccScgNoA9LMm5tmXBE1wdmptxODBNCRqd58+h7Sh/LIFmlgNfxVMT0XG5dqe4GYHIRSGZpoXvecv7hslVybie2KddamH4vK3D1Rwtubb3VZZU52/pmHl+4rxI10serydjMMhbin5sFMSvieVZBiaeka3TnXm1xtumIQVUaeo5amdfbxbLwJKuViQGlGruT2gSE="

addons:
  coverity_scan:
    project:
      name: CE-Programming/CEmu
      description: Build submitted via Travis CI
    build_command_prepend: mkdir build_cov; cd build_cov; qmake ../gui/qt
    build_command: cd build_cov; make -j4 CC=gcc-5 CXX=g++-5 LINK=g++-5
    branch_pattern: coverity_scan

before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo add-apt-repository ppa:beineri/opt-qt551 -y
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-5 gcc-5; export CXX="g++-5" CC="gcc-5"; $CXX --version
- sudo apt-get install -qq qt55base qt55declarative; source /opt/qt55/bin/qt55-env.sh

script:
  - mkdir build
  - cd build
  - qmake ../gui/qt
  - make -j4 CC=gcc-5 CXX=g++-5 LINK=g++-5
  - cd ../core
  - make -j4 CC=gcc-5 CXX=g++-5 LINK=g++-5 clean all

notifications:
  irc:
    channels:
      - "irc.choopa.net#cemu-dev"
    on_success: change
    on_failure: always
    skip_join: true
